### ISSUE TITLE
Error with "status label"

### ISSUE THREAD

**Issue by dcconner** [FlexBE/flexbe_app#2]
Running the example_behavior  with App version 2.0.1
```
chrome-extension://bkpceecdjoihccpjecmbafbjifpefbad/src/ui/ui_runtimecontrol.js:113
		status_label = R.text(R.width / 2, R.height - 30, text)
		                ^

TypeError: Cannot read property 'text' of undefined

    at drawStatusLabel (chrome-extension://bkpceecdjoihccpjecmbafbjifpefbad/src/ui/ui_runtimecontrol.js:113:19)
    at Object.UI.RuntimeControl.displayOutcomeRequest (chrome-extension://bkpceecdjoihccpjecmbafbjifpefbad/src/ui/ui_runtimecontrol.js:721:4)
    at outcome_request_callback (chrome-extension://bkpceecdjoihccpjecmbafbjifpefbad/src/rc/rc_pubsub.js:44:21)
    at process.nextTick (chrome-extension://bkpceecdjoihccpjecmbafbjifpefbad/src/ros/ros_subscriber.js:50:59)

```
In method src/ui/ui_runtimecontrol.js  at L111
```
	var drawStatusLabel = function(text) {
		if (status_label != undefined) status_label.remove();
		status_label = R.text(R.width / 2, R.height - 30, text)
			.attr({'font-size': 16, 'fill': 'gray'});
	}

```
There is no protection against R being undefined and needing to initialized

**Comment by dcconner** [comment]
I should not this does not always happen, but I have seen this error multiple times on different statemachines

**Comment by pschillinger** [comment]
Looks like there is a race condition causing this error if an outcome request is processed before the state display is actually drawn. I will check.
